// Copyright (c) 2018 IBM Corporation and others.
// Licensed under Creative Commons Attribution-NoDerivatives
// 4.0 International (CC BY-ND 4.0)
//   https://creativecommons.org/licenses/by-nd/4.0/
//
// Contributors:
//     IBM Corporation
//


:page-layout: guide
// INSTRUCTION: The project id is the part of the git repository after the guide- and must be specified
// :projectid: github repo name without the `guide-` prefix
:projectid: draft-guide-jpa-intro
// INSTRUCTION: Provide an estimate of how long the guide will take to go through.
:page-duration: 20 minutes
// INSTRUCTION: Provide the date when the guide is published.  Format is YYYY-MM-DD.
:page-releasedate: 2018-07-18
// INSTRUCTION: Provide a description for the guide index page.
:page-description: Learn how to perform CRUD operations using JPA
// INSTUCTION: Please provide relevant tags, try to avoid inventing new ones.
:page-tags: ['JPA']
// INSTRUCTION: Specify the unique name of the guide that is used in the permalink.
:page-related-guides: []
// INSTRUCTION: Specify the slug in the website. This must be unique.
:page-permalink: /guides/{projectid}
// INSTRUCTION: Source the common page elements, clone git@github.com:OpenLiberty/guides-common.git.
:common-includes: https://raw.githubusercontent.com/OpenLiberty/guides-common/master
// INSTRUCTION: You can't have a new line between the attributes and the title.




= Accessing data using Java Persistence API

Learn how to perform CRUD operations using JPA

:eventapp-url: http://localhost:9080/eventmanager.jsf
:get-events-url: http://localhost:9080/events




== What you'll learn

You will learn how to use the Java Persistence API (JPA) to map Java objects to database tables.
JPA is a standard for Object Relational Mapping (ORM) and reduces the burden of having to write
SQL code when performing database operations.

You will learn to use JPA annotations to define a Plain Old Java Object (POJO) class as an entity class.


* NOTE: This section is still in progress


== Getting started

include::{common-includes}/gitclone.adoc[]

=== Try what you’ll build

include::{common-includes}/trywhatyoubuild-intro.adoc[]

Point your browser to the {eventapp-url} URL. As you can see, the event application
currently has no events stored in the database. Go ahead and click on the `Create Event` button located in the left navigation bar. After
entering an event name, location and time, click on `Submit` to persist your event entity to the database. The event is now
stored in the database and is visible in the list of current events. The `Update` button located beside each event allows you to make
modifications to the persisted entity and the `Delete` button allows you to remove entities from the database.

include::{common-includes}/trywhatyoubuild-end.adoc[]


== Defining a JPA entity class

Navigate to the `start` directory to begin.

Before being able to use JPA to store Java objects in a database, we must define an entity class. A JPA entity is a Java object whose
non-transient fields will be persisted to the database. Any POJO class
can be designated as a JPA entity. However, the class must be annotated with the `@Entity` annotation, must not be declared final and must have
a public or protected non-argument constructor. JPA uses a database table for every entity and persisted instances will be represented
as one row in the table.

Add the following JPA annotations to the `Event` class in the `src/main/java/io/openliberty/guides/jpaguide/models/Event.java` file:

[source, Java]
----
include::finish/src/main/java/io/openliberty/guides/jpaguide/models/Event.java[tags=**;]
----

Let's break down the new annotations:

[cols="35, 200", options="header"]
|===
| *Annotation*    | *Description*
| `@Entity` | Declares the class as an entity
| `@Table`  | Specifies details of the table such as name and schema
| `@NamedQuery` | Specfies a query using a static name
| `@Id`       |   Primary key of the entity
| `@GeneratedValue`    | Specifies the generation strategy for the value of the primary key, `strategy = GenerationType.AUTO` indicates that the persistence provider will pick a strategy depending on the database used
| `@Column`    | Specifies that the attribute is mapped to a column in the table, `name` is optional and indicates the name of the column in the table
|===


== Accessing data using JPA

Before being able to access data using JPA, a connection to the database must be established.
An `EntityManager` provides the functionality for performing operations on the database such as
persisting, loading, updating and deleting entities. The `EntityManager`’s configuration is defined
by a persistence unit specified in the `persistence.xml` file.

Create the `src/main/resources/META-INF/persistence.xml` file:

[source, Xml]
----
include::finish/src/main/resources/META-INF/persistence.xml[tags=**;]
----

The persistence unit is defined by the
`<persistence-unit name="jpa-unit" transaction-type="JTA"></persistence-unit>` XML element.
The `name` attribute is required and is used to identify the persistent unit. The `transaction-type=”JTA”`
element specifies to use managed (JTA) transaction management. In a Java EE environment, the default is JTA
if this element is not specified.

A transaction type of JTA requires for a JTA data source to be provided.
This is done via the `<jta-data-source>jdbc/samplejpadatasource</jta-data-source>` element which
specifies the Java Naming and Directory Interface (JNDI) name of the data source that is to be used by
the container. This means that a JDBC connection does not have to be specified in the `persistence.xml`
file and instead the JTA data source can be preconfigured.

Create the `src/main/liberty/config/server.xml` file:

[source, Xml]
----
include::finish/src/main/liberty/config/server.xml[tags=**;]
----

A shared library is defined by the `<library id="derbyJDBCLib"></library>` element.
This element points to the directory of the JDBC driver. The JDBC driver is what enables the
application to interact with the database.

The data source configuration is done within the
`<dataSource id="samplejpadatasource jndiName="jdbc/samplejpadatasource"></dataSource>` element.
The `jndiName="jdbc/samplejpadatasource"` attribute provides a JNDI name for the data source so that
it can be looked up by a component. In this application, the data source is looked up by the
`<jta-data-source>jdbc/samplejpadatasource</jta-data-source>` element in the `persistence.xml` file
mentioned above.

The data source configuration also contains properties such as the database name and whether
to create the database if it does not already exist. These properties can vary based on the
database that is being used.

=== Performing CRUD operations using JPA

CRUD is an abbreviation that defines the four basic functionalities that can be performed on a database: create, read, update and delete.

Create the `src/main/java/io/openliberty/guides/jpaguide/dao/EventDao.java` file:

[source, Java]
----
include::finish/src/main/java/io/openliberty/guides/jpaguide/dao/EventDao.java[tags=**;]
----

Every entity object has a lifecycle that consists of four states: new, managed, removed and detached. Whenever a 
new Event object is created its state will be new, meaning that it is not mapped to a row in the database table and
is not associated with an EntityManger.

The EntityManager manages the lifecycle of entity instances. Every EntityManager instance is associated with a 
persistence context. The persistance context manages a set of entities and is aware of the different states that an entity can have.
In this application the persistence context is container managed, meaning that the EJB container is responsible for
opening and closing the EntityManager. The container is also responsible for transaction boundaries, which is why we do not need to explicitly
begin, commit or rollback transactions. The EJB container will ensure that the required methods are executed within the boundaries
of an active transaction. In order to use the EntityManager at runtime, we must inject it into our EJB component via the `@PersistenceContext` annotation.

The `createEvent` method persists an instance of the Event entity class to the database. By calling the `persist` method on an `EntityManager`, it changes the 
event objects instance from new to managed. This means that the entity is now mapped to a row in the database table and is being managed
by the `EntityManager`.

The `readEvent` method retrieves Event objects from the database. Entity objects are retrieved via the `find` method which requires
both the entity class and the primary key of the object. If the `EntityManager` already manages the searched object in 
its persistence context, then no retrieval from the database is required since the managed Event object will be returned as is.
But, if the `EntityManager` does not already manage the object in its persistence context, a new entity object will be constructed
with data retrieved from the database and returned in a managed state. However, if the Event object is not found in the database, `Null` is returned.

The `updateEvent` method updates an Event object in the database. The EntityManager automatically tracks all managed entity objects
in its persistence context for changes and synchronizes them with the database. The `merge` method will create a new instance of the entity object and make that new instance
managed. However, the entity object passed into the `merge` method is no longer managed. 

The `deleteEvent` method deletes an Event object from the database. By calling the `remove` method on an EntityManager,
the managed entity will be removed from the database and the entity objects state will become removed.

Not that when an entity is no longer associated with a persistence context, its changes will no longer be managed by the EntityManager and the entity
becomes detached.




== Building and running the application

// Use the following include to pull in the Maven build instructions from the guides-common repo.
include::{common-includes}/mvnbuild.adoc[]

When the server is running, visit the {eventapp-url} URL to view the Event Manager application. 

Using the `Create event` button in the left navigation bar you are able to create events that will be persisted to the database. Once 
you have created an event, it will be available to view, update and delete in the `Event list` section.


// Use the following include to pull in the Liberty start/stop server instructions from the
// guides-common repo.
include::{common-includes}/mvncompile.adoc[]

// Instructions to rebuild the application


== Testing the application

Create the `EventAppTest` test class in the `finish/src/test/java/it/io/openliberty/guides/eventapp/tests/EventAppTest.java` file:

[source, Java]
----
include::finish/src/test/java/it/io/openliberty/guides/eventapp/tests/EventAppTest.java[tags=**;]
----

The `testCreatingDeletingNewEvent` method creates a test event and then gets a list of events from the {get-events-url} URL to verify
that the test event was actually persisted to the database. Next, the test event will be deleted from the database and the method will
get a list of events from the {get-events-url} URL once more. This time, when attempting to retrieve the test event, the return value will
be `Null` since it was removed from the database.

The `testUpdatingEvents` method also creates a test event and then gets a list of events from the {get-events-url} URL to verify
that the test event was actually persisted to the database. Next, the method will update the test event with a new name, location and time.
A list of events will be retrieved from the {get-events-url} once again to verify that the event was successfully updated in the database.
Lastly, the updated test event will be deleted from the database and the method will
get a list of events from the {get-events-url} URL one final time. As expected, when attempting to retrieve the test event, the return value will
be `Null` since it was removed from the database.

// Include this for info on how to run the tests
include::{common-includes}/mvnverify.adoc[]

// Including a listing block with test results here
// Show console output of the test results



== Great work! You're done!

// Briefly summarize what the user achieved in this guide (1-2 sentences).

// OPTIONAL: briefly state what the user could do next now that they've learned the
// technologies in this guide.

// Include the below from the guides-common repo to tell users how they can contribute to the guide
include::{common-includes}/finish.adoc[]

// DO NO CREATE ANYMORE SECTIONS AT THIS POINT
// Related guides will be added in automatically here if you included them in ":page-related-guides"
