CREATE DATABASE JPAINTRO;
USE JPAINTRO;
CREATE TABLE Event (eventId INT NOT NULL AUTO_INCREMENT, eventName VARCHAR(45) NULL, eventTime VARCHAR(45) NULL, eventLocation VARCHAR(45) NULL, PRIMARY KEY (eventId));
