name: Test application

on:
  pull_request:
    branches: [ prod, staging ]

jobs:
  check-files:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      canSkip: ${{ steps.Checker.outputs.canSkip }}
    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Get tools
        uses: actions/checkout@v2
        with:
          path: tools/
          repository: openliberty/guides-common
      - id: Checker
        shell: bash
        run: bash ./tools/pr-checker/checker.sh ${{ github.repository }} ${{ github.event.pull_request.number }} | tee checker.log 
      - id: Lint-Code-Base
        if: always()
        uses: github/super-linter@v3.17.0
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ./tools/pr-checker/linters/
          DEFAULT_BRANCH: prod
      - name: Summary
        if: always()
        run: |
            cat ./checker.log |  tail -n +2; echo "====== Super Linter ======"
            cat ./super-linter.log | sed -n '/.*The script has completed.*/,$p' | tail -n +4 | sed  's/.*\(\[[A-Z]\+\]\)/\1/'
            echo "====== Examine logs in Checker and Super-Linter steps for more details ======"
            if [ '${{ steps.Checker.outcome }}' != 'success' ] || [ '${{ steps.Lint-Code-Base.outcome }}' != 'success' ]; then exit 1; fi
  test-app:
    runs-on: ubuntu-latest
    needs: [check-files]
    if: "!contains(needs.check-files.outputs.canSkip, 'true')"
    defaults:
      run:
        working-directory: finish
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        distribution: 'semeru'
        java-version: 21
    - run: unset _JAVA_OPTIONS
    - name: Run tests
      run: sudo -E ../scripts/testApp.sh
    - name: Post tests
      if: always()
      run: |
          logsPath=$(sudo find . -name "console.log");
          sudo cat $logsPath | sudo grep Launching
          sudo chmod -R a+xr $logsPath
    - name: Archive backend logs if failed
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: server-logs
        path: finish/backendServices/target/liberty/wlp/usr/servers/defaultServer/logs/
    - name: Archive frontend logs if failed
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: server-logs
        path: finish/frontendUI/target/liberty/wlp/usr/servers/defaultServer/logs/
